### PR TITLE
fix path regexp for MS

### PR DESCRIPTION
**Pull request by chickpeas**
addressing https://github.com/rxaviers/react-globalize-webpack-plugin/issues/13

### CODE REVIEW

**Comment by rxaviers** [comment]
Will review your PR this weekend. Please, make sure you signed-off you commits after reading https://github.com/rxaviers/react-globalize-webpack-plugin/blob/master/DCO.md.

Thanks!

**Comment by chickpeas** [comment]
@rxaviers are there any news on this?

**Comment by rxaviers** [comment]
Sorry for the delay. We'll also need to update one more occurrence:

``` diff
-     new SkipAMDOfUMDPlugin(/(^|\/)react-globalize($|\/)/)
+     new SkipAMDOfUMDPlugin(/(^|[\/\\])react-globalize($|[\/\\])/)
```

**Comment by rxaviers** [comment]
Thanks! Released as `0.4.2`.

**Pull request closed without merging**
