### PR TITLE
use json-stable-stringify for writing messages

### PR DESCRIPTION
**Pull request by alunny**
See https://www.npmjs.com/package/json-stable-stringify

Also, lock react-globalize-compiler to `^0.0.6` since earlier version have pretty bad bugs.

### CODE REVIEW

**Comment by alunny** [comment]
Please don't merge before I confirm this works on our app.

**Comment by alunny** [comment]
Confirmed, works for us :)

**Comment by rxaviers** [comment]
Awesome you've already tackled this.

About json-stable-stringify, although its goal is exactly what we look for, I'm wondering why its [implementation](https://github.com/substack/json-stable-stringify/blob/master/index.js) is so extensive and it's not something really simple like the below:

``` js
function stableReplacer(k, v) {
  if(Array.isArray(v)) {
    return v.sort();
  } else if (v && typeof v === 'object') {
    return Object.keys(v).sort().reduce(function(sum, i) {
      sum[i] = v[i]; return sum
    }, {})};
  return v;
}

module.exports = function stringify(input, space) {
  return JSON.stringify(input, stableReplacer, space)
}
```

**Comment by rxaviers** [comment]
Note to self, this fixes #8

**Comment by alunny** [comment]
json-stable-stringify is a bit more robust and flexible - it has options for dealing with cyclic objects, custom serializers, polyfills Array.isArray, Object.keys, etc etc.

None of which is necessary for our use case, but this code doesn't have anything to do with react, globalize, or webpack, so I'd rather use the library. One less thing to maintain :smiley:

**Comment by rxaviers** [comment]
Yeap, not having to maintain it is probably worth it. Also, it might not be a performance bottleneck given the frequency it's used.

:+1: thanks!

**Pull request closed without merging**
