### PR TITLE
move globalize-webpack-plugin to a peer dep

### PR DESCRIPTION
**Pull request by jbellenger**
The direct dependency of RGWP on GWP has made it difficult to test changes to globalize-webpack-plugin in the build process at twitter. 
Here's a proposal for moving globalize-webpack-plugin to be a peer dependency to make testing easier.

### CODE REVIEW

**Comment by rxaviers** [comment]
Oh that's tricky...

I feel your pain, because of the various modules; but making it a peer dependency isn't technically correct, because there's an actual direct dependency of this module on GWP.

Given peer deps aren't installed automatically, this approach could be problematic for regular usage, where developers add RGWP in their dependencies, but wouldn't add GWP as well.

Thoughts?

**Comment by jbellenger** [comment]
Ah, gotcha. It may be that peerDependencies isn't the right mechanism; maybe npm link is the more correct approach here.
I'll give that a shot.

**Comment by rxaviers** [comment]
Ok, keep me posted please. Thanks

**Comment by jbellenger** [comment]
Closing.

**Pull request closed without merging**
